a = int(input())
b = int(input())
c = int(input())
x = int(input())
y = int(input())
z = int(input())
n1 = (a // x) * (b // y) * (c // z)
n2 = (a // x) * (b // z) * (c // y)
n3 = (a // y) * (b // z) * (c // x)
n4 = (a // y) * (b // x) * (c // z)
n5 = (a // z) * (b // x) * (c // y)
n6 = (a // z) * (b // y) * (c // x)
print(max(n1, n2, n3, n4, n5, n6))
